### ISSUE TITLE
Inconsistent fuse bytes

### ISSUE THREAD

**Issue by maxgerhardt** [MCUdude/microUPDIcore#7]
Per 

https://github.com/MCUdude/microUPDIcore/blob/03939dccb908259125fdd4fa3e1ec2402d3e0f7f/avr/boards.txt#L13-L17

but then 

https://github.com/MCUdude/microUPDIcore/blob/03939dccb908259125fdd4fa3e1ec2402d3e0f7f/avr/firmwares/CLI%20flash%20script/Load_firmware.sh#L26-L31

These values seem really different to me. Is this correct?

**Comment by MCUdude** [comment]
Thanks for reporting! The fuses in the Load_firmware.sh is definitly wrong. I'll fix this, however, the script isn't really used bu the IDE, it was somthing I threw together while working on this core.

**Comment by ChrisKnightley** [comment]
Is the value of L fuse and H fuse swapped in the your commit?

**Comment by MCUdude** [comment]
> Is the value of L fuse and H fuse swapped in the your commit?

You're absolutely right, I can't believe I did this! I'll fix it right away
