### ISSUE TITLE
Any source code for this?

### ISSUE THREAD

**Issue by jxltom** [MCUdude/microUPDIcore#8]
I've only found the hex file. I'm curious are there any source code for this? THX!

**Comment by MCUdude** [comment]
Nope, sorry. I've asked an Atmel developer that was involved in developing the mEDBG firmware, but they won't release it because there is apparently some secret sauce in it...

**Comment by jxltom** [comment]
OK got it.

May I know where is the hex file in the repo from?

**Comment by MCUdude** [comment]
The hex file was copied from an Atmel Studio 7 installation, where I've modified the EEPROM contents to give it its own serial number, and to disable "safe mode". This means it can turn a UPDI pin into a GPIO.

**Comment by jxltom** [comment]
Many thanks!
